//
//  CartProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CartWireframeProtocol: class {

}
//MARK: Presenter -
protocol CartPresenterProtocol: class {

}

//MARK: Interactor -
protocol CartInteractorProtocol: class {

  var presenter: CartPresenterProtocol?  { get set }
}

//MARK: View -
protocol CartViewProtocol: class {

  var presenter: CartPresenterProtocol?  { get set }
}
