//
//  CartPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartPresenter: CartPresenterProtocol {

    weak private var view: CartViewProtocol?
    var interactor: CartInteractorProtocol?
    private let router: CartWireframeProtocol

    init(interface: CartViewProtocol, interactor: CartInteractorProtocol?, router: CartWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
