//
//  AlertPopupPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 07/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AlertPopupPresenter: AlertPopupPresenterProtocol {

    weak private var view: AlertPopupViewProtocol?
    private let interactor: AlertPopupInteractorProtocol
    private let router: AlertPopupWireframeProtocol

    init(interface: AlertPopupViewProtocol, interactor: AlertPopupInteractorProtocol, router: AlertPopupWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }

}
