//
//  BusinessSearchPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 11/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessSearchPresenter: BusinessSearchPresenterProtocol {

    weak private var view: BusinessSearchViewProtocol?
    var interactor: BusinessSearchInteractorProtocol?
    private let router: BusinessSearchWireframeProtocol

    init(interface: BusinessSearchViewProtocol, interactor: BusinessSearchInteractorProtocol?, router: BusinessSearchWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
	
	func addToFavorites(business: Business) {
		
		interactor?.addToFavorites(business: business)
		
	}
	
	func showBusinessPage(business:Business) {
		router.showBusinessPage(business: business)
	}
	
	func removedFromFavorites(business: Business) {
		
		
	}

}
