//
//  BusinessSearchViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 11/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessSearchViewController: UIViewController, BusinessSearchViewProtocol {

	@IBOutlet weak var searchTextField: UITextField!
	@IBOutlet weak var categoriesCollectionView: UICollectionView!
	@IBOutlet weak var searchButton: UIButton!
	
	var presenter: BusinessSearchPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
		
		categoriesCollectionView.register(UINib(nibName: "ServiceCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "ServiceCollectionViewCell")
		
		
		let cellSize = CGSize(width:Device.TheCurrentDeviceWidth/2 , height:62.5)
		let layout = UICollectionViewFlowLayout()
		layout.itemSize = cellSize
		layout.scrollDirection = .horizontal
		layout.minimumLineSpacing = 5
		layout.minimumInteritemSpacing = 0
		layout.sectionInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
		categoriesCollectionView.collectionViewLayout = layout
		
    }

	@IBAction func search(_ sender: Any) {
		
		
		
	}
	
	
}
