//
//  ForgotPasswordInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordInteractor: ForgotPasswordInteractorProtocol {

    weak var presenter: ForgotPasswordPresenterProtocol?
	
	func didTapSendButton(email:String) {
		
		PetbookingAPI.sharedInstance.resetPassword(email) { (success, message) in
			
			if success {
				self.presenter?.resetPasswordWithSuccess()
			} else {
				self.presenter?.resetPasswordWithError()
			}
			
		}
		
	}
}
