//
//  AlertPopupProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 07/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AlertPopupWireframeProtocol: class {

}
//MARK: Presenter -
protocol AlertPopupPresenterProtocol: class {

}

//MARK: Interactor -
protocol AlertPopupInteractorProtocol: class {

  var presenter: AlertPopupPresenterProtocol?  { get set }
}

//MARK: View -
protocol AlertPopupViewProtocol: class {

  var presenter: AlertPopupPresenterProtocol?  { get set }
}
