//
//  ScheduleCalendarRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScheduleCalendarRouter: ScheduleCalendarWireframeProtocol {
    
    weak var viewController: UIViewController?
    
	static func createModule(business:Business, service:Service, serviceCategory:ServiceCategory, pet:Pet) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ScheduleCalendarViewController(nibName: nil, bundle: nil)
				view.business = business
				view.serviceCategory = serviceCategory
				view.service = service
				view.pet = pet
        let interactor = ScheduleCalendarInteractor()
        let router = ScheduleCalendarRouter()
        let presenter = ScheduleCalendarPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
