//
//  ScheduleCalendarProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ScheduleCalendarWireframeProtocol: class {

}
//MARK: Presenter -
protocol ScheduleCalendarPresenterProtocol: class {

}

//MARK: Interactor -
protocol ScheduleCalendarInteractorProtocol: class {

  var presenter: ScheduleCalendarPresenterProtocol?  { get set }
}

//MARK: View -
protocol ScheduleCalendarViewProtocol: class {

  var presenter: ScheduleCalendarPresenterProtocol?  { get set }
}
