//
//  ScheduleCalendarInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScheduleCalendarInteractor: ScheduleCalendarInteractorProtocol {

    weak var presenter: ScheduleCalendarPresenterProtocol?
}
