//
//  BusinessInformationProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BusinessInformationWireframeProtocol: class {
  
}
//MARK: Presenter -
protocol BusinessInformationPresenterProtocol: class {
  
}

//MARK: Interactor -
protocol BusinessInformationInteractorProtocol: class {
  
  var presenter: BusinessInformationPresenterProtocol?  { get set }
}

//MARK: View -
protocol BusinessInformationViewProtocol: class {
  
  var presenter: BusinessInformationPresenterProtocol?  { get set }
}
