//
//  BusinessInformationViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MapKit

class BusinessInformationViewController: UIViewController, BusinessInformationViewProtocol {

	
	@IBOutlet weak var favoriteButton: UIButton!
	@IBOutlet weak var businessNameLabel: UILabel!
	@IBOutlet weak var descriptionLabel: UILabel!
	@IBOutlet weak var phoneNumberLabel: UILabel!
	@IBOutlet weak var websiteLabel: UILabel!
	@IBOutlet weak var addressLabel: UILabel!
	@IBOutlet weak var distanceLabel: UILabel!
	@IBOutlet weak var businessImageView: UIView!
	@IBOutlet weak var mapView: MKMapView!
	@IBOutlet weak var distanceView: UIView!
	
	var business:Business! = Business()
	
	var presenter: BusinessInformationPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
		
		
			businessNameLabel.text = business.name
			descriptionLabel.text = business.businessDescription
			phoneNumberLabel.text = business.phone
		distanceLabel.text = "\(business.distance)km"
		distanceLabel.sizeToFit()
		distanceView.round()
		distanceView.setBorder(width: 1, color: .red)
		websiteLabel.text = business.website
		addressLabel.text = "\(business.street), \(business.streetNumber), \(business.neighborhood)"
		
		let coordinateRegion = MKCoordinateRegionMakeWithDistance(business.location, 1000, 1000)
		
		mapView.setRegion(coordinateRegion, animated: false)
		
		let annotation = MKPointAnnotation()
		
		annotation.coordinate = CLLocationCoordinate2D(latitude: business.location.latitude, longitude: business.location.longitude)
		mapView.addAnnotation(annotation)
    }

}

extension BusinessInformationViewController: MKMapViewDelegate {
	
	func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
		
		if !(annotation is MKPointAnnotation) {
			return nil
		}
		
		var annotationView = mapView.dequeueReusableAnnotationView(withIdentifier: "demo")
		if annotationView == nil {
			annotationView = MKAnnotationView(annotation: annotation, reuseIdentifier: "demo")
			annotationView!.canShowCallout = true
		}
		else {
			annotationView!.annotation = annotation
		}
		
		annotationView!.image = UIImage(named: "business_pin")
		
		return annotationView
		
		
	}
	
}
