//
//  BusinessInformationInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessInformationInteractor: BusinessInformationInteractorProtocol {

    weak var presenter: BusinessInformationPresenterProtocol?
}

enum SocialNetworkEnum:String {
	case facebook = "facebook", instagram = "instagram", snapchat = "snapchat", twitter = "twitter", googleplus = "googleplus"
}
