//
//  BusinessInformationPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessInformationPresenter: BusinessInformationPresenterProtocol {

    weak private var view: BusinessInformationViewProtocol?
    var interactor: BusinessInformationInteractorProtocol?
    private let router: BusinessInformationWireframeProtocol

    init(interface: BusinessInformationViewProtocol, interactor: BusinessInformationInteractorProtocol?, router: BusinessInformationWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
