//
//  MyPetsProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 20/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MyPetsWireframeProtocol: class {
    func showAddPet()
}

//MARK: Presenter -
protocol MyPetsPresenterProtocol: class {
    
    func reloadTableData()
    func fillTableData(petList:PetList)
    func didTapAddPet()
}

//MARK: Interactor -
protocol MyPetsInteractorProtocol: class {
    
    var presenter: MyPetsPresenterProtocol?  { get set }
    
    func reloadTableData()
}

//MARK: View -
protocol MyPetsViewProtocol: class {
    
    var presenter: MyPetsPresenterProtocol?  { get set }
    
    func fillTableData(petList:PetList)
}
