//
//  MyPetsInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 20/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MyPetsInteractor: MyPetsInteractorProtocol {

    weak var presenter: MyPetsPresenterProtocol?
	
	func reloadTableData() {
		PetbookingAPI.sharedInstance.getUserPets { (petList, message) in
			guard let petList = petList else { return }
			
			self.presenter?.fillTableData(petList: petList)
		}
	}
}
