//
//  AlertPopupRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 07/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AlertPopupRouter: AlertPopupWireframeProtocol {
	
	weak var viewController: UIViewController?
	
	static func createModule(title:String, message:String) -> UIViewController {
		// Change to get view from storyboard if not using progammatic UI
		let view = AlertPopupViewController(nibName: nil, bundle: nil)
		view.view.frame = CGRect(x:0,y:0, width: Device.TheCurrentDeviceWidth, height: Device.TheCurrentDeviceHeight)
		view.titleLabel.text = title
		view.messageLabel.text = message
		let interactor = AlertPopupInteractor()
		let router = AlertPopupRouter()
		let presenter = AlertPopupPresenter(interface: view, interactor: interactor, router: router)
		
		view.presenter = presenter
		interactor.presenter = presenter
		router.viewController = view
		
		return view
	}
}
