//
//  LoginPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 28/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import ALLoadingView

class LoginPresenter: LoginPresenterProtocol {

    weak private var view: LoginViewProtocol?
    private let interactor: LoginInteractorProtocol
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorProtocol, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }
	
	func didTapLoginButton(email:String?, password:String?) {
		ALLoadingView.manager.showLoadingView(ofType: .basic, windowMode: .fullscreen)
		interactor.didTapLoginButton(email: email, password: password)
	}
	
	func didTapFacebookLoginButton() {
		interactor.didTapFacebookLoginButton()
	}
	
	func didTapSignupButton() {
		router.didTapSignupButton()
	}
	
	func didTapForgotPasswordButton() {
		router.didTapForgotPasswordButton()
	}
	
	func didCompleteFacebookLoginWithSuccess() {
		ALLoadingView.manager.hideLoadingView(withDelay: 1) { 
			self.router.didCompleteFacebookLoginWithSuccess()
		}
	}
	
	func didCompleteFacebookLoginWithError(error: Error?) {
        ALLoadingView.manager.hideLoadingView()
		view?.didCompleteFacebookLoginWithError(error: error)
	}
	
	func didCompleteLoginWithSuccess() {
		ALLoadingView.manager.hideLoadingView(withDelay: 1) {
			self.router.didCompleteFacebookLoginWithSuccess()
		}
    }
	
	func didCompleteLoginWithError(error:Error?) {
        ALLoadingView.manager.hideLoadingView()
		view?.didCompleteLoginWithError(error: error)
	}
	
	func registerNewUserWithFacebookData() {
		router.registerNewUserWithFacebookData()
	}
	
	func showLoading() {
		ALLoadingView.manager.showLoadingView(ofType: .basic, windowMode: .fullscreen)
	}
}
