//
//  LoginInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 28/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FacebookCore
import FacebookLogin

class LoginInteractor: LoginInteractorProtocol {
	
	weak var presenter: LoginPresenterProtocol?
	
	func didTapLoginButton() {
		
	}
	
	func didTapFacebookLoginButton() {
		
		let loginManager = LoginManager()
		loginManager.logIn([.publicProfile, .email], viewController: nil) { (loginResult) in
			
			switch loginResult {
			case .failed(let error):
				self.presenter?.didCompleteFacebookLoginWithError(error: error)
				break
			case .cancelled:
				break
			case .success(let grantedPermissions, let declinedPermissions, let accessToken):
				
				PetbookingAPI.sharedInstance.loginWithFacebook(accessToken.authenticationToken, completion: { (success, message) in
					
					if success {
						self.presenter?.didCompleteFacebookLoginWithSuccess()
					}
					
				})
				
				self.presenter?.didCompleteFacebookLoginWithSuccess()
				break
			}
			
		}
		
		
		}
		
		func didTapSignupButton() {
			
			
		}
		
		func didTapForgotPasswordButton() {
			
		}
}
