//
//  LoginProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 28/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginWireframeProtocol: class {

	func didTapForgotPasswordButton()
	
	func didTapSignupButton()
	
	func didCompleteFacebookLoginWithSuccess()
	
	func registerNewUserWithFacebookData()
}
//MARK: Presenter -
protocol LoginPresenterProtocol: class {
	
	func didTapLoginButton(email:String?, password:String?)
	
	func didTapFacebookLoginButton()
	
	func didTapSignupButton()
	
	func didTapForgotPasswordButton()
	
	func didCompleteFacebookLoginWithSuccess()
	
	func didCompleteFacebookLoginWithError(error:Error?)
	
	func didCompleteLoginWithSuccess()
	
	func didCompleteLoginWithError(error:Error?)
	
	func registerNewUserWithFacebookData()

}

//MARK: Interactor -
protocol LoginInteractorProtocol: class {

  var presenter: LoginPresenterProtocol?  { get set }
	
	func didTapLoginButton(email:String?, password:String?)
	
	func didTapFacebookLoginButton()
	
	func didTapSignupButton()
	
	func didTapForgotPasswordButton()
}

//MARK: View -
protocol LoginViewProtocol: class {

  var presenter: LoginPresenterProtocol?  { get set }
	
	func didCompleteFacebookLoginWithError(error:Error?)
	
	func didCompleteLoginWithError(error:Error?)
	
}
