//
//  LoginViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 28/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {

	@IBOutlet weak var loginButton: UIButton!
	@IBOutlet weak var signupButton: UIButton!
	@IBOutlet weak var facebookLoginButton: UIButton!
	@IBOutlet weak var forgotPasswordButton: UIButton!
	@IBOutlet weak var emailTextField: UITextField!
	@IBOutlet weak var passwordTextField: UITextField!
	
	
	var presenter: LoginPresenterProtocol?

	override func viewDidLoad() {
		super.viewDidLoad()
		hideKeyboardWhenTappedAround()
    }
	
	override func viewDidLayoutSubviews() {
		super.viewDidLayoutSubviews()
		setupButtons()
	}
	
	func setupButtons() {
		loginButton.roundButton()
		signupButton.roundButton()
		facebookLoginButton.roundButton()
		signupButton.buttonWithBorder(width: 2, color: .white)
	}

	@IBAction func login(_ sender: Any) {
	}
	
	@IBAction func facebookLogin(_ sender: Any) {
		presenter?.didTapFacebookLoginButton()
	}
	
	@IBAction func signup(_ sender: Any) {
	}
	
	@IBAction func forgotPassword(_ sender: Any) {
	}
	
}
