//
//  BusinessListViewControllerViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 20/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreLocation

class BusinessListViewControllerViewController: UIViewController, BusinessListViewControllerViewProtocol {
	
	var presenter: BusinessListViewControllerPresenterProtocol?
	var locationManager:CLLocationManager?
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		locationManager = CLLocationManager()
		
		locationManager?.delegate = self
		
		// Ask for Authorisation from the User.
		self.locationManager?.requestAlwaysAuthorization()
		
		// For use in foreground
		self.locationManager?.requestWhenInUseAuthorization()
		
		if CLLocationManager.locationServicesEnabled() {
			locationManager?.delegate = self
			locationManager?.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
			locationManager?.startUpdatingLocation()
		}
		
	}
	
	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
		
		
	}
	
}

extension BusinessListViewControllerViewController: CLLocationManagerDelegate {
	
	
	func locationManager(_ manager: CLLocationManager, didFailWithError error: Error)
	{
		locationManager?.stopUpdatingLocation()
		
		print(error)
	}
	
	func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation])
	{
		locationManager?.stopUpdatingLocation()
		
		let locationArray = locations as NSArray
		let locationObj = locationArray.lastObject as! CLLocation
		let coord = locationObj.coordinate
		print(coord.latitude)
		print(coord.longitude)
		
		PetbookingAPI.sharedInstance.getBusinessList(coordinate: coord) { (businessList, msg) in
			
			print(msg)
			
		}
		
	}
	
}
