//
//  BusinessListViewControllerInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 20/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import CoreLocation

class BusinessListViewControllerInteractor: BusinessListViewControllerInteractorInputProtocol {
	
	weak var presenter: BusinessListViewControllerInteractorOutputProtocol?
	
	func getBusinessByCoordinates(coordinates:CLLocationCoordinate2D, page:Int) {
		
		PetbookingAPI.sharedInstance.getBusinessList(coordinate: coordinates, page:page) { (businessList, msg) in
			
			guard let businessList = businessList else {
				return
			}
			
			self.presenter?.updateBusinessList(businessList: businessList)
			
		}
		
	}
	
	func addToFavorites(business: Business) {
		
		if business.isFavorite {
			
			PetbookingAPI.sharedInstance.removeBusinessFromFavorite(business: business, completion: { (success, message) in
				
				if success {
					business.isFavorite = false
				}
				
			})
			
		} else {
			
			PetbookingAPI.sharedInstance.addBusinessToFavorite(business: business) { (success, message) in
				
				if success {
					business.isFavorite = true
				}
				
			}
		}
		
	}
}

enum BusinessListType {
	case list, map
}
