//
//  BusinessListViewControllerPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 20/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import  CoreLocation

class BusinessListViewControllerPresenter: BusinessListViewControllerPresenterProtocol, BusinessListViewControllerInteractorOutputProtocol {

    weak private var view: BusinessListViewControllerViewProtocol?
    var interactor: BusinessListViewControllerInteractorInputProtocol?
    private let router: BusinessListViewControllerWireframeProtocol

    init(interface: BusinessListViewControllerViewProtocol, interactor: BusinessListViewControllerInteractorInputProtocol?, router: BusinessListViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
	
	func getBusinessByCoordinates(coordinates:CLLocationCoordinate2D) {
		interactor?.getBusinessByCoordinates(coordinates: coordinates)
	}
	
	func updateBusinessList(businessList:BusinessList) {
		view?.updateBusinessList(businessList: businessList)
	}

}
