//
//  BusinessListViewControllerRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 20/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessListViewControllerRouter: BusinessListViewControllerWireframeProtocol {
	
	weak var viewController: UIViewController?
	
    static func createModule(businessListType: BusinessListType, from service: ServiceCategory? = nil) -> UIViewController {
		// Change to get view from storyboard if not using progammatic UI
<<<<<<< HEAD
        
        var view: BusinessListViewControllerViewProtocol!
        
        switch businessListType {
        case .list, .favorites:
            view = BusinessListViewControllerViewController(nibName: nil, bundle: nil)
        default:
            view = BusinessMapListViewController(nibName: nil, bundle: nil)
        }
        
        view.service = service
=======
		let view: BusinessListViewControllerViewProtocol = (businessListType == .list || businessListType == .favorites) ? BusinessListViewControllerViewController(nibName: nil, bundle: nil) : BusinessMapListViewController(nibName: nil, bundle: nil)
		
>>>>>>> 4aaf2d5fb0901efab15a9bd7b4907370f1bcd0b9
		view.businessListType = businessListType
		
		let interactor = BusinessListViewControllerInteractor()
		interactor.businessListType = businessListType
		let router = BusinessListViewControllerRouter()
		let presenter = BusinessListViewControllerPresenter(interface: view, interactor: interactor, router: router)
		
		view.presenter = presenter
		interactor.presenter = presenter
		router.viewController = view as? UIViewController
		
		return view as! UIViewController
	}
	
<<<<<<< HEAD
	func showBusinessPage(business: Business) {
=======
	func showBusinessPage(business:Business) {
>>>>>>> 4aaf2d5fb0901efab15a9bd7b4907370f1bcd0b9
		let homeBusiness = HomeBusinessRouter.createModule(business: business)
		
		self.viewController?.navigationController?.pushViewController(homeBusiness, animated: true)
	}
}
