//
//  ForgotPasswordPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import ALLoadingView

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol {

    weak private var view: ForgotPasswordViewProtocol?
    private let interactor: ForgotPasswordInteractorProtocol
    private let router: ForgotPasswordWireframeProtocol

    init(interface: ForgotPasswordViewProtocol, interactor: ForgotPasswordInteractorProtocol, router: ForgotPasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }
	
	func didTapSendButton(email:String) {
		ALLoadingView.manager.showLoadingView(ofType: .basic, windowMode: .fullscreen)
		interactor.didTapSendButton(email: email)
	}
	
	func resetPasswordWithSuccess() {
		ALLoadingView.manager.hideLoadingView()
		view?.resetPasswordWithSuccess()
	}
	
	func resetPasswordWithError() {
		ALLoadingView.manager.hideLoadingView()
		view?.resetPasswordWithError()
	}

}
