//
//  AddPetViewControllerRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 25/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddPetViewControllerRouter: AddPetViewControllerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AddPetViewControllerViewController(nibName: nil, bundle: nil)
        let interactor = AddPetViewControllerInteractor()
        let router = AddPetViewControllerRouter()
        let presenter = AddPetViewControllerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
	
	func didSavePetWithSuccess() {
		viewController?.navigationController?.popViewController(animated: true)
	}
	
}
