//
//  AddPetViewControllerProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 25/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AddPetViewControllerWireframeProtocol: class {

}
//MARK: Presenter -
protocol AddPetViewControllerPresenterProtocol: class {

}

//MARK: Interactor -
protocol AddPetViewControllerInteractorProtocol: class {

  var presenter: AddPetViewControllerPresenterProtocol?  { get set }
}

//MARK: View -
protocol AddPetViewControllerViewProtocol: class {

  var presenter: AddPetViewControllerPresenterProtocol?  { get set }
}
