//
//  AddPetViewControllerInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 25/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddPetViewControllerInteractor: AddPetViewControllerInteractorProtocol {

    weak var presenter: AddPetViewControllerPresenterProtocol?
	
	func savePet(pet:Pet) {
		
		
		PetbookingAPI.sharedInstance.createPet(pet: pet) { (petList, message) in
			
			
			
		}
		
	}
}

enum PetPickerType {
	case gender, petType, petSize, breed, coat, temper
}
