//
//  AddPetViewControllerInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 25/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddPetViewControllerInteractor: AddPetViewControllerInteractorProtocol {
	
	weak var presenter: AddPetViewControllerPresenterProtocol?
	
	var petViewType:PetViewType?
	
	func savePet(pet:Pet) {
		
		if petViewType == .create {
			
			PetbookingAPI.sharedInstance.createPet(pet: pet) { (pet, message) in
				
				if pet != nil {
					self.presenter?.didSavePetWithSuccess()
				} else {
					self.presenter?.didSavePetWithError(message: message)
				}
				
			}
		} else {
			PetbookingAPI.sharedInstance.updatePet(pet: pet) { (pet, message) in
				
				if pet != nil {
					self.presenter?.didSavePetWithSuccess()
				} else {
					self.presenter?.didSavePetWithError(message: message)
				}
				
			}
		}
		
	}
}

enum PetPickerType {
	case gender, petType, petSize, breed, coat, temper
}

enum PetViewType {
	case create, edit
}
