//
//  SignupProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignupWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignupPresenterProtocol: class {

}

//MARK: Interactor -
protocol SignupInteractorProtocol: class {

  var presenter: SignupPresenterProtocol?  { get set }
}

//MARK: View -
protocol SignupViewProtocol: class {

  var presenter: SignupPresenterProtocol?  { get set }
}
