//
//  SignupPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignupPresenter: SignupPresenterProtocol {

    weak private var view: SignupViewProtocol?
    private let interactor: SignupInteractorProtocol
    private let router: SignupWireframeProtocol

    init(interface: SignupViewProtocol, interactor: SignupInteractorProtocol, router: SignupWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }

}
