//
//  SignupPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import ALLoadingView

class SignupPresenter: SignupPresenterProtocol {
	
	
	
	weak private var view: SignupViewProtocol?
	private let interactor: SignupInteractorProtocol
	private let router: SignupWireframeProtocol
	
	init(interface: SignupViewProtocol, interactor: SignupInteractorProtocol, router: SignupWireframeProtocol) {
		self.view = interface
		self.interactor = interactor
		self.router = router
		
		self.interactor.presenter = self
	}
	
	func fillFields() {
		interactor.fillFields()
	}
	
	func setProfileImageView(urlString:String) {
		ALLoadingView.manager.hideLoadingView()
		view?.setProfileImageView(urlString: urlString)
	}
	
	func setNameLabel(name:String) {
		
		view?.setNameLabel(name: name)
	}
	
	func setEmail(email:String) {
		
		view?.setEmail(email: email)
	}
	
	func fillAdrressWithZipcode(zipcode:String) {
		interactor.fillAdrressWithZipcode(zipcode: zipcode)
	}
	
	func fillAdrressFields(street:String, neighborhood:String, city:String, state:String) {
		view?.fillAdrressFields(street: street, neighborhood: neighborhood, city: city, state: state)
	}
	
}
