//
//  SignupRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignupRouter: SignupWireframeProtocol {
	
	weak var viewController: UIViewController?
	
	static func createModule(signupType:SignupType = .email) -> UIViewController {
		// Change to get view from storyboard if not using progammatic UI
		let view = SignupViewController(nibName: nil, bundle: nil)
		let interactor = SignupInteractor()
		interactor.signupType = signupType
		view.signupType = signupType
		let router = SignupRouter()
		let presenter = SignupPresenter(interface: view, interactor: interactor, router: router)
		
		view.presenter = presenter
		interactor.presenter = presenter
		router.viewController = view
		
		return view
	}
	
	func createUserWithSuccess(){
		
		let viewController = HomeContentViewControllerRouter.createModule()
		
		self.viewController?.present(viewController, animated: true, completion: nil)
	}
	
	func updatedUserWithSuccess(){
		
		self.viewController?.navigationController?.popViewController(animated: true)
		
	}
}
