//
//  SignupViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignupViewController: UIViewController, SignupViewProtocol {

	
	@IBOutlet weak var profilePictureView: UIView!
	@IBOutlet weak var profilePictureImageView: UIImageView!
	@IBOutlet weak var profilePictureFrameView: UIView!
	@IBOutlet weak var fullNameTextField: UITextField!
	@IBOutlet weak var cpfTextField: UITextField!
	@IBOutlet weak var birthdayTextField: UITextField!
	@IBOutlet weak var passwordTextField: UITextField!
	@IBOutlet weak var confirmPasswordTextField: UITextField!
	@IBOutlet weak var emailTextField: UITextField!
	@IBOutlet weak var mobileNumberTextField: UITextField!
	@IBOutlet weak var saveButton: UIButton!
	
	var presenter: SignupPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
		
		self.navigationController?.isNavigationBarHidden = false
		self.title = "Preencha os seus dados"
		hideKeyboardWhenTappedAround()
				setupView()
    }
	
	func setupView() {
		profilePictureView.round()
		profilePictureFrameView.setBorder(width: 2, color: .white)
		profilePictureFrameView.round()
		saveButton.round()
	}

	
	@IBAction func save(_ sender: Any) {
	}
	
}
