//
//  SignupProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 29/04/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignupWireframeProtocol: class {
    func createUserWithSuccess()
    func updatedUserWithSuccess()
}

//MARK: Presenter -
protocol SignupPresenterProtocol: class {
    
    func fillFields()
    func setProfileImageView(withUrlString urlString: String)
    func setName(_ name: String)
    func setEmail(_ email: String)
    func setMobile(_ mobile: String)
    func createUser(name: String, email: String, mobile: String, password: String, avatar: String?)
    func createUserWithSuccess()
    func updatedUserWithSuccess()
    func createUserWithError()
}

//MARK: Interactor -
protocol SignupInteractorProtocol: class {
    
    var presenter: SignupPresenterProtocol?  { get set }
    
    func fillFields()
    func createUser(name: String, email: String, mobile: String, password: String, avatar: String?)
}

//MARK: View -
protocol SignupViewProtocol: class {
    
    var presenter: SignupPresenterProtocol?  { get set }
    
    func setProfileImageView(withUrlString urlString: String)
    func setName(_ name: String)
    func setEmail(_ email: String)
    func setMobile(_ mobile: String)
}
