//
//  HomeBusinessPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeBusinessPresenter: HomeBusinessPresenterProtocol {

    weak private var view: HomeBusinessViewProtocol?
    var interactor: HomeBusinessInteractorProtocol?
    private let router: HomeBusinessWireframeProtocol

    init(interface: HomeBusinessViewProtocol, interactor: HomeBusinessInteractorProtocol?, router: HomeBusinessWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
