//
//  HomeBusinessProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeBusinessWireframeProtocol: class {

}
//MARK: Presenter -
protocol HomeBusinessPresenterProtocol: class {

}

//MARK: Interactor -
protocol HomeBusinessInteractorProtocol: class {

  var presenter: HomeBusinessPresenterProtocol?  { get set }
}

//MARK: View -
protocol HomeBusinessViewProtocol: class {

  var presenter: HomeBusinessPresenterProtocol?  { get set }
}
