//
//  HomeBusinessRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeBusinessRouter: HomeBusinessWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(business: Business) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomeBusinessViewController(nibName: nil, bundle: nil)
        view.business = business
        let interactor = HomeBusinessInteractor()
        let router = HomeBusinessRouter()
        let presenter = HomeBusinessPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
