//
//  BusinessServicesRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessServicesRouter: BusinessServicesWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(with business: Business, from service: ServiceCategory? = nil) -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = BusinessServicesViewController(nibName: nil, bundle: nil)
        view.business = business
        view.service = service
        let interactor = BusinessServicesInteractor()
        let router = BusinessServicesRouter()
        let presenter = BusinessServicesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
