//
//  BusinessServicesProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BusinessServicesWireframeProtocol: class { }

//MARK: Presenter -
protocol BusinessServicesPresenterProtocol: class {
    
    func getPets()
    func loadPets(petList: PetList)
    func getServices(business: Business, service: ServiceCategory, pet: Pet?)
    func getCategories(business: Business)
    func loadServices(serviceList: ServiceList)
    func loadCategories(serviceCategoryList: ServiceCategoryList)
}

//MARK: Interactor -
protocol BusinessServicesInteractorProtocol: class {
    
    var presenter: BusinessServicesPresenterProtocol?  { get set }
    
    func getPets()
    func getServices(business: Business, service: ServiceCategory, pet: Pet?)
    func getCategories(business: Business)
}

//MARK: View -
protocol BusinessServicesViewProtocol: class {
    
    var presenter: BusinessServicesPresenterProtocol?  { get set }
    var category: ServiceCategory? { get set }
    
    func loadPets(petList: PetList)
    func loadServices(serviceList: ServiceList)
    func loadCategories(serviceCategoryList: ServiceCategoryList)
}
