//
//  BusinessServicesInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessServicesInteractor: BusinessServicesInteractorProtocol {

    weak var presenter: BusinessServicesPresenterProtocol?
	
	
	func getPets() {
		
		PetbookingAPI.sharedInstance.getUserPets { (petList, message) in
			
			guard let petList = petList else {
				return
			}
			
			self.presenter?.loadPets(petList: petList)
			
		}
		
	}
	
	func getCategories(business:Business) {
		
		PetbookingAPI.sharedInstance.getBusinessServicesCategoryList(business: business) { (serviceCategoryList, message) in
			
			guard let serviceCategoryList = serviceCategoryList else {
				return
			}
			
			self.presenter?.loadCategories(serviceCategoryList: serviceCategoryList)
			
		}
		
	}
	
	func getServices(business: Business, service: ServiceCategory, pet:Pet) {
		
		PetbookingAPI.sharedInstance.getBusinessServicesList(business: business, service: service, pet:pet) { (serviceList, message) in
			
			guard let serviceList = serviceList else {
				return
			}
			
			self.presenter?.loadServices(serviceList: serviceList)
			
		}
	}
	
}
