//
//  BusinessServicesPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 24/07/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BusinessServicesPresenter: BusinessServicesPresenterProtocol {

    weak private var view: BusinessServicesViewProtocol?
    var interactor: BusinessServicesInteractorProtocol?
    private let router: BusinessServicesWireframeProtocol

    init(interface: BusinessServicesViewProtocol, interactor: BusinessServicesInteractorProtocol?, router: BusinessServicesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
	
	func getPets() {
		interactor?.getPets()
	}
	
	func loadPets(petList: PetList) {
		view?.loadPets(petList: petList)
	}
	
	func getCategories(business: Business) {
		interactor?.getCategories(business: business)
	}
	
	func getServices(business: Business, service: ServiceCategory, pet:Pet) {
		interactor?.getServices(business: business, service: service, pet:pet)
	}
	
	func loadCategories(serviceCategoryList: ServiceCategoryList) {
		view?.loadCategories(serviceCategoryList: serviceCategoryList)
	}
	
	func loadServices(serviceList: ServiceList) {
		view?.loadServices(serviceList: serviceList)
	}
}
