//
//  CartWebPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartWebPresenter: CartWebPresenterProtocol {

    weak private var view: CartWebViewProtocol?
    var interactor: CartWebInteractorProtocol?
    private let router: CartWebWireframeProtocol

    init(interface: CartWebViewProtocol, interactor: CartWebInteractorProtocol?, router: CartWebWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
