//
//  CartWebRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartWebRouter: CartWebWireframeProtocol {
    
    weak var viewController: UIViewController?
    
	static func createModule(cart:Cart) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CartWebViewController(nibName: nil, bundle: nil)
				view.cart = cart
        let interactor = CartWebInteractor()
        let router = CartWebRouter()
        let presenter = CartWebPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
