//
//  CartWebProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CartWebWireframeProtocol: class {

}
//MARK: Presenter -
protocol CartWebPresenterProtocol: class {

}

//MARK: Interactor -
protocol CartWebInteractorProtocol: class {

  var presenter: CartWebPresenterProtocol?  { get set }
}

//MARK: View -
protocol CartWebViewProtocol: class {

  var presenter: CartWebPresenterProtocol?  { get set }
}
