//
//  CartWebViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 03/08/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CartWebViewController: UIViewController, CartWebViewProtocol {

	@IBOutlet weak var webView: UIWebView!
	var presenter: CartWebPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
