//
//  AlertPopupViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 07/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AlertPopupViewController: UIViewController, AlertPopupViewProtocol {
	
	@IBOutlet weak var popupContentContainerView: UIView!
	
	@IBOutlet weak var titleLabel: UILabel!
	
	@IBOutlet weak var messageLabel: UILabel!
	
	@IBOutlet weak var dismissButton: UIButton!
	
	var presenter: AlertPopupPresenterProtocol?
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		popupContentContainerView.layer.masksToBounds = true
		popupContentContainerView.layer.cornerRadius = 10
		dismissButton.round()
	}
	
	
	@IBAction func dismissAlert(_ sender: Any) {
		dismiss(animated: true, completion: nil)
	}
	
}

extension AlertPopupViewController: MIBlurPopupDelegate {
	
	var popupView: UIView {
		return popupContentContainerView ?? UIView()
	}
	var blurEffectStyle: UIBlurEffectStyle {
		return .dark
	}
	var initialScaleAmmount: CGFloat {
		return 0.0
	}
	var animationDuration: TimeInterval {
		return 0.5
	}
	
}
