//
//  SelectPhotoSourcePopupProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 06/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SelectPhotoSourcePopupWireframeProtocol: class { }

//MARK: Presenter -
protocol SelectPhotoSourcePopupPresenterProtocol: class { }

//MARK: Interactor -
protocol SelectPhotoSourcePopupInteractorProtocol: class {
    var presenter: SelectPhotoSourcePopupPresenterProtocol?  { get set }
}

//MARK: View -
protocol SelectPhotoSourcePopupViewProtocol: class {
    var presenter: SelectPhotoSourcePopupPresenterProtocol?  { get set }
    var delegate: SelectPhotoSourcePopupActionProtocol?  { get set }
}

protocol SelectPhotoSourcePopupActionProtocol: class {
    func showCamera()
    func showAlbum()
}
