//
//  SelectPhotoSourcePopupPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 06/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SelectPhotoSourcePopupPresenter: SelectPhotoSourcePopupPresenterProtocol {

    weak private var view: SelectPhotoSourcePopupViewProtocol?
    private let interactor: SelectPhotoSourcePopupInteractorProtocol
    private let router: SelectPhotoSourcePopupWireframeProtocol

    init(interface: SelectPhotoSourcePopupViewProtocol, interactor: SelectPhotoSourcePopupInteractorProtocol, router: SelectPhotoSourcePopupWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }

}
