//
//  SelectPhotoSourcePopupRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 06/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SelectPhotoSourcePopupRouter: SelectPhotoSourcePopupWireframeProtocol {
	
	weak var viewController: UIViewController?
	
	static func createModule(delegate:SelectPhotoSourcePopupActionProtocol? = nil) -> UIViewController {
		// Change to get view from storyboard if not using progammatic UI
		let view = SelectPhotoSourcePopupViewController(nibName: nil, bundle: nil)
		view.view.frame = CGRect(x:0,y:0, width: Device.TheCurrentDeviceWidth, height: Device.TheCurrentDeviceHeight)
		view.delegate = delegate
		let interactor = SelectPhotoSourcePopupInteractor()
		let router = SelectPhotoSourcePopupRouter()
		let presenter = SelectPhotoSourcePopupPresenter(interface: view, interactor: interactor, router: router)
		
		view.presenter = presenter
		interactor.presenter = presenter
		router.viewController = view
		
		return view
	}
}
