//
//  SelectPhotoSourcePopupViewController.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 06/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SelectPhotoSourcePopupViewController: UIViewController, SelectPhotoSourcePopupViewProtocol {

	@IBOutlet weak var libraryButton: UIButton!
	@IBOutlet weak var cameraButton: UIButton!
	@IBOutlet weak var cancelButton: UIButton!
	
	@IBOutlet weak var popupContentContainerView: UIView!
	
	var presenter: SelectPhotoSourcePopupPresenterProtocol?
	
	var delegate: SelectPhotoSourcePopupActionProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
		
		popupContentContainerView.layer.masksToBounds = true
		popupContentContainerView.layer.cornerRadius = 10
		
		libraryButton.round()
		cameraButton.round()
		cancelButton.round()
		cancelButton.setBorder(width: 1, color: .white)
		
		
    }

	@IBAction func showAlbum(_ sender: Any) {
		dismiss(animated: true) {
			self.delegate?.showAlbum()
		}
	}
	
	@IBAction func showCamera(_ sender: Any) {
		
		dismiss(animated: true) {
			self.delegate?.showCamera()
		}
		
	}
	@IBAction func cancel(_ sender: Any) {
		dismiss(animated: true)
	}
	
	@IBAction func tappedOutsidePopup(_ sender: Any) {
		
		dismiss(animated: true)
	}
	
	
}

extension SelectPhotoSourcePopupViewController: MIBlurPopupDelegate {
	
	var popupView: UIView {
		return popupContentContainerView ?? UIView()
	}
	var blurEffectStyle: UIBlurEffectStyle {
		return .dark
	}
	var initialScaleAmmount: CGFloat {
		return 0.0
	}
	var animationDuration: TimeInterval {
		return 0.5
	}
	
}
