//
//  HomeContentViewControllerPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 14/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContentViewControllerPresenter: HomeContentViewControllerPresenterProtocol {

    weak private var view: HomeContentViewControllerViewProtocol?
    private let interactor: HomeContentViewControllerInteractorProtocol
    private let router: HomeContentViewControllerWireframeProtocol

    init(interface: HomeContentViewControllerViewProtocol, interactor: HomeContentViewControllerInteractorProtocol, router: HomeContentViewControllerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }    
}
