//
//  HomeContentViewControllerInteractor.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 14/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import ALLoadingView

class HomeContentViewControllerInteractor: HomeContentViewControllerInteractorProtocol {

    weak var presenter: HomeContentViewControllerPresenterProtocol?
}
