//
//  HomeContentViewControllerProtocols.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 14/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeContentViewControllerWireframeProtocol: class { }

//MARK: Presenter -
protocol HomeContentViewControllerPresenterProtocol: class {
    func getReview()
    func loadReview(reviewList: ReviewableList)
}

//MARK: Interactor -
protocol HomeContentViewControllerInteractorProtocol: class {
    var presenter: HomeContentViewControllerPresenterProtocol? { get set }
    
    func getReview()
}

//MARK: View -
protocol HomeContentViewControllerViewProtocol: class {
    var presenter: HomeContentViewControllerPresenterProtocol? { get set }
    
    func showReviewable(_ review: ReviewableList)
}
