//
//  HomeContentViewControllerRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 14/06/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContentViewControllerRouter: HomeContentViewControllerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomeContentViewController(nibName: nil, bundle: nil)
        let interactor = HomeContentViewControllerInteractor()
        let router = HomeContentViewControllerRouter()
        let presenter = HomeContentViewControllerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
