//
//  SideMenuRouter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 18/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SideMenu

class SideMenuRouter: SideMenuWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SideMenuViewController(nibName: nil, bundle: nil)
        let interactor = SideMenuInteractor()
        let router = SideMenuRouter()
        let presenter = SideMenuPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
	
	func didTapLogout() {
		
		let loginViewController = LoginRouter.createModule()
		
		self.viewController?.navigationController?.pushViewController(loginViewController, animated: true)
		
	}
}
