//
//  SideMenuPresenter.swift
//  petbooking-ios-v2
//
//  Created Ryniere S Silva on 18/05/17.
//  Copyright © 2017 Pet Booking Serviços e Desenvolvimento de Softwares SA. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SideMenuPresenter: SideMenuPresenterProtocol {

    weak private var view: SideMenuViewProtocol?
    private let interactor: SideMenuInteractorProtocol
    private let router: SideMenuWireframeProtocol

    init(interface: SideMenuViewProtocol, interactor: SideMenuInteractorProtocol, router: SideMenuWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }
	
	func didTapLogout() {
		
		interactor.didTapLogout()
		router.didTapLogout()
		
	}

}
